New swimming effects
gta-chaos-mod/Trilogy-ASI-Script pull request #195
Opened 2023-01-06 15:47 UTC by gromchek

`Swim like Tommy` - player takes full health damage in ~5 sec
`Disable swimming` - disable controls in water

2023-01-06 16:09 UTC, Lordmau5 requested changes

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/DisableSwimmingEffect.cpp
> +        if (player && !FindPlayerVehicle (-1, false))
Please use an early return here - `if (!player || FindPlayerVehicle(-1, false)) return;

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/DisableSwimmingEffect.cpp
> +            if (!pad)
Please have the `return;` be on the same line without the curly brackets

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/DisableSwimmingEffect.cpp
> +            if (cond)
You might be able to just do `pad->DisablePlayerControls = cond;` here

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/SwimLikeTommyEffect.cpp
> +        if (player && !FindPlayerVehicle (-1, false))
Same here, early return please

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/SwimLikeTommyEffect.cpp
> +            if (!pad)
Same as in the other file, return on the same line

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/SwimLikeTommyEffect.cpp
> +            if (cond)
And same as in the other file, too - Can just do `pad->DisablePlayerControls = cond;` probably

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/SwimLikeTommyEffect.cpp
> +        if (wait > 0)
Return on the same line, please

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/SwimLikeTommyEffect.cpp
> +        if (!player)
Return on the same line, please

2023-01-06 16:09 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/SwimLikeTommyEffect.cpp
> +DEFINE_EFFECT (SwimLikeTommyEffect, "effect_swim_like_tommy", GROUP_HEALTH);
Seeing as you modify the health *and* controls, I'd prefer if you could do `GROUP_HEALTH | GROUP_CONTROLS` so it's in both groups

2023-01-06 16:11 UTC, Lordmau5 commented
Oh also I forgot to add that in the review, you can credit yourself at the top of the files if you want
Honestly, I'd even prefer that :)

2023-01-06 17:32 UTC, gromchek commented
Fixed

2023-01-06 17:49 UTC, Lordmau5 commented
Dunno why it failed with the compilation... I managed to compile it just fine locally

I'll get this merged and also push the effects in the GUI, but I'm not sure when I'll be able to get out a new version with these

2023-01-06 17:49 UTC, merged

2023-01-07 09:52 UTC, Lordmau5 commented
Alright so I went ahead and checked if the effects even work properly just now LMAO
Should've done that before...

Either way - `Swim Like Tommy` drains the player's health when they are in the water, but neither of the 2 effects actually disable swimming controls, or controls at all, for me... Which is interesting. I know other effects like `Let's Take A Break` do it properly so I'm pretty confused myself ...