New effect: `Randomize player stats` #196
gta-chaos-mod/Trilogy-ASI-Script pull request #214
Opened 2023-01-09 22:14 UTC by gromchek

I haven't checked all the stats (e.g. girlfriend relationship level, lung capacity, respect), but these work well.
The sex appeal stat seems work more complicated than just change value.
I noticed that the change stats after start new game but before notify tooltip ("Use WASD to move Carl" something like that) maybe work inncorectly.

2023-01-09 22:21 UTC, Lordmau5 commented
Oh dear god why does this have to be 22 *separate* effects, please don't.

When I read that issue / effect suggestion I thought of a list of stats that make sense to be randomized (as you did as well in your implementation) - but definitely not all of this crazyness haha

I'd recommend doing just 1 One-Time effect that randomizes them once. Maybe also a timed effect that reverts back to what they were before (Shouldn't matter *too much* if they suddenly get a huge bump from e.g. Flight or Driving School)

2023-01-09 22:34 UTC, gromchek commented
Ok. Updated.
Anyway, in the future we can easily split stats into different categories

2023-01-09 22:50 UTC, Lordmau5 requested changes

2023-01-09 22:50 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/RandomizePlayerStatsEffect.cpp
> +    void
New line after the closing curly bracket missing

2023-01-09 22:50 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/RandomizePlayerStatsEffect.cpp
> +    void
New line after the closing curly bracket missing

2023-01-09 22:50 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/RandomizePlayerStatsEffect.cpp
> +            CStats::SetStatValue (stat, inst->Random (min, max));
New line after the closing curly bracket missing

2023-01-09 22:50 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/RandomizePlayerStatsEffect.cpp
> +        GameUtil::RebuildPlayer ();
New line after the closing curly bracket missing

2023-01-09 22:50 UTC, Lordmau5 commented on src/gtasa/effects/custom/player/RandomizePlayerStatsEffect.cpp
> +            GameUtil::RebuildPlayer ();
New line after the closing curly bracket missing

2023-01-09 22:51 UTC, Lordmau5 commented
Requested a few style changes. Could it be that whatever you're using for editing isn't properly taking the `.clang-format` file into account?

When I saved your previous 2 effects in VSCode they were reformatted a bit... Might also be extra settings in my VSCode that I'm not aware of

2023-01-09 23:00 UTC, gromchek commented
> Could it be that whatever you're using for editing isn't properly taking the .clang-format file into account?

I use Visual Studio (not VSCode) and clang-format doesn't seem to work properly every time.

2023-01-10 10:48 UTC, Lordmau5 commented
> I found it: I need to press Ctrl+K+D manually to format

Is that native in Visual Studio or did you have to install an extension? Maybe there's a "Format on Save" option somewhere, might be nice to have for this project (not trying to force you to use it globally haha)

2023-01-10 14:12 UTC, gromchek commented
> Is that native in Visual Studio or did you have to install an extension? Maybe there's a "Format on Save" option somewhere, might be nice to have for this project (not trying to force you to use it globally haha)

This helped me https://stackoverflow.com/a/66058774
Now it works

2023-01-11 13:09 UTC, Lordmau5 approved these changes

2023-01-11 13:09 UTC, merged

2023-12-07 15:35 UTC, Jersukai commented
Not sure if this is the right place to report this but there's a bug with the timed effect. If you load a save when it's active you get the original stats back.